<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BADAN PENANGGULANGAN BENCANA DAERAH</name>
   <tag></tag>
   <elementGuidId>2c2f0bef-8388-4d39-8b95-1fd45ec04c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-2107 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-2107']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b75a6120-6772-4f49-9ed0-f4d5b8f3fa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>37acb861-e969-438e-9947-effba7a61d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BADAN PENANGGULANGAN BENCANA DAERAH</value>
      <webElementGuid>0dd71fe9-6358-42c2-980d-18cdb2b8e279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-2107&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>4161c6f8-21ca-4bef-b9af-1dfa55033808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-2107']/a</value>
      <webElementGuid>ce8069f8-7649-47fd-b9e8-8bf17aa947d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BADAN PENANGGULANGAN BENCANA DAERAH')]</value>
      <webElementGuid>2a4faa3f-466b-44ed-ad6d-acd878cc7bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bappeda.makassar.go.id'])[1]/following::a[1]</value>
      <webElementGuid>66aa6e53-5d1a-4e8d-bb3e-7a191e76bf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[123]/following::a[2]</value>
      <webElementGuid>1f92516c-31a2-4cb9-a268-31a830eed177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[46]/preceding::a[1]</value>
      <webElementGuid>c826e45e-451c-494c-9b56-12a758a8f831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[124]/preceding::a[1]</value>
      <webElementGuid>355196bc-b517-4ecd-8aa6-80340b4d5efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BADAN PENANGGULANGAN BENCANA DAERAH']/parent::*</value>
      <webElementGuid>2a231018-d5d5-4f25-acc4-ef74ddf6fecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[177]</value>
      <webElementGuid>e16b5688-10ee-49db-97e5-2febf64f88ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div/section/div/div/div/div/div/div/div[7]/div/a</value>
      <webElementGuid>2dff28b0-f7e5-4575-9a42-d5ff437d7996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'BADAN PENANGGULANGAN BENCANA DAERAH' or . = 'BADAN PENANGGULANGAN BENCANA DAERAH')]</value>
      <webElementGuid>e57a1c4c-27fc-4f0b-9d74-e3aae315191c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
