<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DINAS PEMUDA DAN OLAHRAGA</name>
   <tag></tag>
   <elementGuidId>15a2bd4e-27dd-41d9-a4ce-0324808d7cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17614 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17614']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>758872d8-4ae1-4711-bb30-5f352e868406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>2ac1b711-0959-486f-b5e4-3fde814906e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DINAS PEMUDA DAN OLAHRAGA</value>
      <webElementGuid>0567f161-2846-454d-aea2-bd40ab95de54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17614&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>b9b8cf52-3b46-4bcc-8758-fae974f3e440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17614']/a</value>
      <webElementGuid>01dced67-84e1-4863-95f8-d2ae63e7717b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DINAS PEMUDA DAN OLAHRAGA')]</value>
      <webElementGuid>1c758c64-36cb-4548-8163-d716728f6aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='siga.dp3amakassar.com'])[1]/following::a[1]</value>
      <webElementGuid>ff32ee90-fef4-463a-ad39-906c9bcc37ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[39]/following::a[2]</value>
      <webElementGuid>797ce753-ba8b-443e-991e-6d6bebee9c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[14]/preceding::a[1]</value>
      <webElementGuid>5bb32c06-79a4-41c8-a1e7-91ae73bbb915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[40]/preceding::a[1]</value>
      <webElementGuid>04b8b740-01b6-4be0-bd52-cb77f89acb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DINAS PEMUDA DAN OLAHRAGA']/parent::*</value>
      <webElementGuid>7d788a28-ffe2-4fd9-aaaf-2456a0944089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[101]</value>
      <webElementGuid>aee4e3fd-8090-472d-9eb0-b3c540dec5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/a</value>
      <webElementGuid>f4cf8744-e0ea-470f-9917-0a925bac22d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'DINAS PEMUDA DAN OLAHRAGA' or . = 'DINAS PEMUDA DAN OLAHRAGA')]</value>
      <webElementGuid>5dd9a48e-d02c-460b-baa8-12634b6424cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
