<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DINAS PERIKANAN DAN PERTANIAN</name>
   <tag></tag>
   <elementGuidId>f33808e8-846f-4f9f-832c-a8cb5017d425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17620 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17620']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5c235d3-662d-4409-bb3f-bc05e83de5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>c902d34e-d19f-4552-be55-333a52885d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DINAS PERIKANAN DAN PERTANIAN</value>
      <webElementGuid>a6420f05-5fb2-48ca-a8fd-6a218cd3bd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17620&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>c23e578b-e57b-47a9-8789-6caf35e3bc24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17620']/a</value>
      <webElementGuid>cdc08bfa-24c8-4849-9036-55400fddfcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DINAS PERIKANAN DAN PERTANIAN')]</value>
      <webElementGuid>ab9bcf36-e763-4134-8e69-f15853fc86de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dishub.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>bc406cb3-916b-445d-b912-3dfdf832e78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[57]/following::a[2]</value>
      <webElementGuid>47637df9-3175-4bdc-9350-f32f9cde9b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[20]/preceding::a[1]</value>
      <webElementGuid>0a0a04b4-416e-407c-8660-aba740c0a5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[58]/preceding::a[1]</value>
      <webElementGuid>7bb041a6-02e6-4cb2-ab2b-be3b53dfdc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DINAS PERIKANAN DAN PERTANIAN']/parent::*</value>
      <webElementGuid>56d287c6-8752-48f2-93c9-157cf838f41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[119]</value>
      <webElementGuid>b6fd5000-9bcc-4144-89fc-62c9938551cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/a</value>
      <webElementGuid>a4dc64f3-1a14-4769-8359-4049b37ffb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'DINAS PERIKANAN DAN PERTANIAN' or . = 'DINAS PERIKANAN DAN PERTANIAN')]</value>
      <webElementGuid>169a8df6-7ee4-4c2b-8630-50cc88912ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
