<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DINAS PENGENDALIAN PENDUDUK DAN KB</name>
   <tag></tag>
   <elementGuidId>e9003563-cf2e-46ab-998a-f18a1e2dbd3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17617 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17617']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae254454-7265-41b9-b4cf-03192d4e4f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>9b648dd8-293b-40cf-bbf3-b1ba6a247ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DINAS PENGENDALIAN PENDUDUK DAN KB</value>
      <webElementGuid>b4215a08-567d-4e9d-b980-06ce3201ad13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17617&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>82d5b6a1-c893-4f53-bd79-2ed122b5fce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17617']/a</value>
      <webElementGuid>6e42e44c-17dd-41f6-884d-8aec8fd05e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DINAS PENGENDALIAN PENDUDUK DAN KB')]</value>
      <webElementGuid>8d0d91bb-8add-414b-806d-0307ce9abb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='distaru.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>498d0819-72dd-4439-a183-61164c68d972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[48]/following::a[2]</value>
      <webElementGuid>3f5c0a8f-3069-460d-8c13-9e98446f4cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[17]/preceding::a[1]</value>
      <webElementGuid>f93bb568-c1bf-4cd1-b36d-7ca61549e1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[49]/preceding::a[1]</value>
      <webElementGuid>72f59636-449b-4adb-9461-9efb2a275137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DINAS PENGENDALIAN PENDUDUK DAN KB']/parent::*</value>
      <webElementGuid>f2dbc618-9316-44ea-8c01-bb8b72156933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[110]</value>
      <webElementGuid>8a84ba92-0cb2-499c-acf6-65eb780baff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/a</value>
      <webElementGuid>e4aab656-aa4b-40ab-85b1-e48eff053ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'DINAS PENGENDALIAN PENDUDUK DAN KB' or . = 'DINAS PENGENDALIAN PENDUDUK DAN KB')]</value>
      <webElementGuid>c68600ac-eb7f-4674-b438-ff277ea13701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
