<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DINAS PEMADAM KEBAKARAN</name>
   <tag></tag>
   <elementGuidId>588b1a2f-4f6c-49bd-90f6-602a8786fae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17612 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17612']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93a4d906-a874-4365-b9e0-b90a4b5ac0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>a4d29d42-d1ea-4699-8c35-2e9740b912aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DINAS PEMADAM KEBAKARAN</value>
      <webElementGuid>eeb3fcb8-bdd5-4a32-8f27-a60ddc5975c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17612&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>3bb61b36-c2bd-4f67-89bf-eb536d0608a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17612']/a</value>
      <webElementGuid>1d5ce140-75c6-4969-b1de-a17586bf1a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DINAS PEMADAM KEBAKARAN')]</value>
      <webElementGuid>d2b5754b-d83d-4547-aba4-ef87d86dd938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dpu.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>6c00188e-f9e9-4601-93c7-c66d1336900a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[33]/following::a[2]</value>
      <webElementGuid>8f7f5864-02d1-4a46-8a77-43c1c0964f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[12]/preceding::a[1]</value>
      <webElementGuid>ea0531d4-2348-4e18-b50a-4ded05e8b9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[34]/preceding::a[1]</value>
      <webElementGuid>d11906e6-4937-4bde-b80e-219badf27a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DINAS PEMADAM KEBAKARAN']/parent::*</value>
      <webElementGuid>68a044b9-84e2-40ee-bcd8-8193a991b57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[95]</value>
      <webElementGuid>40274963-6ca1-4ada-90c5-410176c9866b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/a</value>
      <webElementGuid>d71edb4e-e99d-4053-abd4-8bd625596d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'DINAS PEMADAM KEBAKARAN' or . = 'DINAS PEMADAM KEBAKARAN')]</value>
      <webElementGuid>91c4c058-e532-490f-bfc5-ad89709bec3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
