<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DINAS KOPERASI, USAHA KECIL DAN MENENGAH</name>
   <tag></tag>
   <elementGuidId>b16f1c74-5e7f-481b-808c-a32d6147f66a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-1768 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-1768']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>336e099e-b4b2-418a-835d-0018e090e068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>0e184337-ca3a-4561-8f40-04fbb46a218c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DINAS KOPERASI, USAHA KECIL DAN MENENGAH</value>
      <webElementGuid>89be0322-1ee6-458a-ab88-7402a767ddee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-1768&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>3a8dc0ba-43bd-46d5-a293-7ecb92c83255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-1768']/a</value>
      <webElementGuid>ddc54db7-a0f3-4a17-b71c-a770f3487d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DINAS KOPERASI, USAHA KECIL DAN MENENGAH')]</value>
      <webElementGuid>cba459aa-eb21-4e75-b37e-a4b444c65f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='diskominfo.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>0217559c-02aa-4770-b974-4f189c396f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[21]/following::a[2]</value>
      <webElementGuid>c1cd6867-1e7e-43c6-832e-36b0310b8a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[8]/preceding::a[1]</value>
      <webElementGuid>2e2640c7-c3c3-4251-96c5-319825847ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[22]/preceding::a[1]</value>
      <webElementGuid>9dfdca3c-9bc6-48c0-bef1-321446d2449d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DINAS KOPERASI, USAHA KECIL DAN MENENGAH']/parent::*</value>
      <webElementGuid>7f1b190b-7599-42e6-87ba-23cb74bd64a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[83]</value>
      <webElementGuid>cd89631a-fa4f-4533-97a6-a1a42a7ec9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/a</value>
      <webElementGuid>4aec0fa4-58dc-4840-a568-e962a1de3b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'DINAS KOPERASI, USAHA KECIL DAN MENENGAH' or . = 'DINAS KOPERASI, USAHA KECIL DAN MENENGAH')]</value>
      <webElementGuid>79375f88-538c-438c-8911-77ca8e44def6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
