<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INSPEKTORAT KOTA MAKASSAR</name>
   <tag></tag>
   <elementGuidId>01c9c11a-cac7-4b00-909a-6ec0584c9553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17625 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17625']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d3c9c54-ee7c-4082-b91c-38ef9de3756b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>b2f535b7-904e-4cbe-9166-e978fef939a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INSPEKTORAT KOTA MAKASSAR</value>
      <webElementGuid>aacdca28-4061-4f60-888c-0c3a03f908c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17625&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>c7b04390-8799-44e4-94c2-4962ad8488a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17625']/a</value>
      <webElementGuid>2b3a0245-c780-4624-ac38-2e95fae026ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INSPEKTORAT KOTA MAKASSAR')]</value>
      <webElementGuid>8f1a193b-7a32-4244-9032-92a77114b3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dinsos.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>2c64ec37-cdb9-4444-bda2-0061579b6123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[72]/following::a[2]</value>
      <webElementGuid>ba6143d4-4fc8-42db-abae-a23488c94f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[25]/preceding::a[1]</value>
      <webElementGuid>64948076-67e5-400a-9bd0-211a0e62b8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[73]/preceding::a[1]</value>
      <webElementGuid>7e8cedeb-c56e-4a60-b307-a790e75f09d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INSPEKTORAT KOTA MAKASSAR']/parent::*</value>
      <webElementGuid>dad00c89-5903-4500-8261-c5bf0819e01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[133]</value>
      <webElementGuid>1da7ee74-655e-4b62-aaba-a04d6605effe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/div/a</value>
      <webElementGuid>55eaa7d8-2c44-42c6-871a-577ec2fc86d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'INSPEKTORAT KOTA MAKASSAR' or . = 'INSPEKTORAT KOTA MAKASSAR')]</value>
      <webElementGuid>a2eea5c8-6662-4502-8080-d24e94a0b9b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
