<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KECAMATAN WAJO</name>
   <tag></tag>
   <elementGuidId>55259bb2-c98e-40a0-9bce-91daf9a12e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-18215 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-18215']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ec40305-cee2-4c3e-8836-39e0d379c055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>39d93326-ce7a-44f7-afb8-a365cfefde34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KECAMATAN WAJO</value>
      <webElementGuid>20bfe219-983c-4f9a-9917-a0ac5b54e379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-18215&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>f21042e5-73c3-4494-bc6b-83fcad4192ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-18215']/a</value>
      <webElementGuid>398e3253-13ac-43c8-941e-fbb472f5e8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KECAMATAN WAJO')]</value>
      <webElementGuid>905c6795-eb6f-4675-a77f-b604c0849393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ujungtanahkec.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>b5e0ea2f-8165-47c4-a2ad-aac3d74d79a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[168]/following::a[2]</value>
      <webElementGuid>4a76c53d-e439-4d4e-a766-32b2a552f6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[61]/preceding::a[1]</value>
      <webElementGuid>2a4ebaa8-4a68-40ff-a673-de55fbbaf4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[169]/preceding::a[1]</value>
      <webElementGuid>957323c6-0b78-4c52-bf4b-6bc1918486f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KECAMATAN WAJO']/parent::*</value>
      <webElementGuid>6e24d6b0-7664-4229-84c8-cf04453eb777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[222]</value>
      <webElementGuid>2bae18cb-bc0d-47b3-84f5-96a30160eb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/div/section/div/div/div/div/div/div/div[15]/div/a</value>
      <webElementGuid>3f2e2589-c678-40b9-b689-3979e527ee46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'KECAMATAN WAJO' or . = 'KECAMATAN WAJO')]</value>
      <webElementGuid>5f78cfa6-9d9d-4ba1-9700-1dca510954b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
