<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KECAMATAN UJUNG TANAH</name>
   <tag></tag>
   <elementGuidId>33e15093-6d39-467a-8718-15442b988cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-18214 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-18214']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7093202c-efdf-435e-8942-3ad065aff47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>af4805a0-0251-4683-9101-fb71edd5d5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KECAMATAN UJUNG TANAH</value>
      <webElementGuid>75c629da-b418-43a7-88f8-81dc2202aa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-18214&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>70f52ce5-8935-469c-b040-e4975df34970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-18214']/a</value>
      <webElementGuid>d4207752-22ac-46c1-9de4-fb45916fece5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KECAMATAN UJUNG TANAH')]</value>
      <webElementGuid>16aba08e-d509-4573-94be-c8c6acd8bebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ujungpandangkec.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>79ccf217-3626-4de3-a20d-f825007625ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[165]/following::a[2]</value>
      <webElementGuid>48c0fc3c-d9d0-46f6-835f-6240182a16fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[60]/preceding::a[1]</value>
      <webElementGuid>98304d34-0b68-483e-a0b5-f9de490dd2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[166]/preceding::a[1]</value>
      <webElementGuid>fc1b3634-a100-4b93-968b-d8ae0787f725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KECAMATAN UJUNG TANAH']/parent::*</value>
      <webElementGuid>2a794ecb-b962-4a72-b036-7f648b0ba5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[219]</value>
      <webElementGuid>a3a414af-9b5f-4641-9ed2-8a213925cdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/div/section/div/div/div/div/div/div/div[14]/div/a</value>
      <webElementGuid>4e77c653-2e24-44eb-ba0a-ec1a12ec6831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'KECAMATAN UJUNG TANAH' or . = 'KECAMATAN UJUNG TANAH')]</value>
      <webElementGuid>07b1caf1-7299-4c61-9410-606d24eb6f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
