<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SEKRETARIAT DPRD</name>
   <tag></tag>
   <elementGuidId>edc6cf63-0ca0-47cc-a173-f27fa5086436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17626 > a.elementor-toggle-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17626']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64a91ec5-209c-41bf-9e66-5bfaf2f33eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-title</value>
      <webElementGuid>bdf66f99-b9cd-41bf-8384-343e283f720f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEKRETARIAT DPRD</value>
      <webElementGuid>bc4496dd-cba9-46e4-a6ee-1e91e9e7c542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17626&quot;)/a[@class=&quot;elementor-toggle-title&quot;]</value>
      <webElementGuid>c64b8d9d-cbe6-48a3-8041-d6addae8185b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17626']/a</value>
      <webElementGuid>0d556358-8766-476e-b988-4dcc79b773ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SEKRETARIAT DPRD')]</value>
      <webElementGuid>47b1fab7-397a-45fe-9869-d662552f61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inspektorat.makassarkota.go.id'])[1]/following::a[1]</value>
      <webElementGuid>de95da19-5cd1-4d8d-b814-43c92e840fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[75]/following::a[2]</value>
      <webElementGuid>f6726eca-398f-491b-9e51-556dfb5d8e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[26]/preceding::a[1]</value>
      <webElementGuid>a15c4fc4-a559-41a7-88cb-f4474001c520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[76]/preceding::a[1]</value>
      <webElementGuid>a01b633e-5c70-4ca0-bd71-9e7e064b8466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEKRETARIAT DPRD']/parent::*</value>
      <webElementGuid>c01c7de8-a0b9-48cf-86a1-d231ed2f6370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[136]</value>
      <webElementGuid>74105982-1b9c-4efa-8b2b-5952cf14bd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/a</value>
      <webElementGuid>e7a5e74b-d650-4ef8-bece-f247037d4c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'SEKRETARIAT DPRD' or . = 'SEKRETARIAT DPRD')]</value>
      <webElementGuid>70f4cee8-180f-4ab9-bc36-7c11c60085ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
