<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Telepon Sekarang</name>
   <tag></tag>
   <elementGuidId>3ae45661-1142-4995-b2e3-9c36b86d5f02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.uc_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uc_hover_text_reveal_content_box_elementor15248']/div/div/div[3]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e79b4663-1c56-4584-8761-ec8183ce734a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>callto:112</value>
      <webElementGuid>53efe46d-52a2-4cb6-8313-b836c51b2f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uc_btn</value>
      <webElementGuid>fffcfae5-3b12-4071-8a8a-086cb3363991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Telepon Sekarang</value>
      <webElementGuid>255fa72a-7f40-453e-b18c-8792bb179762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uc_hover_text_reveal_content_box_elementor15248&quot;)/div[@class=&quot;uc_long_content_box_holder&quot;]/div[@class=&quot;uc_long_content_box_box&quot;]/div[@class=&quot;uc_box_content&quot;]/div[@class=&quot;uc_hidden_content&quot;]/a[@class=&quot;uc_btn&quot;]</value>
      <webElementGuid>f2959aee-1eb1-4bc0-8dfe-60c0c9fdded9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uc_hover_text_reveal_content_box_elementor15248']/div/div/div[3]/div[2]/a</value>
      <webElementGuid>411ab594-af2d-4b4b-a6bd-67541bc3cc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Telepon Sekarang')]</value>
      <webElementGuid>b0372961-6861-431e-942f-d77edb58e7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NTPD 112'])[1]/following::a[1]</value>
      <webElementGuid>4f2a4095-5874-418f-b67f-9bcf188d2410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENGUMUMAN'])[1]/following::a[1]</value>
      <webElementGuid>f349d2f8-085a-4519-a83d-aa6b5cdf2769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info COVID-19'])[1]/preceding::a[1]</value>
      <webElementGuid>f54f18a9-aab8-49b4-a683-aa381e63a43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[1]/preceding::a[1]</value>
      <webElementGuid>c3b6469e-e4a2-43b1-9407-ff1c64ec7226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Telepon Sekarang']/parent::*</value>
      <webElementGuid>ed6b6051-3f80-43ad-8419-dc6e4c323efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'callto:112')]</value>
      <webElementGuid>426fde12-950a-4b20-8e4f-b4ae7ea9a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>f9ae60a4-39f4-4e3f-8bf0-077f6659e2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'callto:112' and (text() = 'Telepon Sekarang' or . = 'Telepon Sekarang')]</value>
      <webElementGuid>72d54f78-f476-4f2b-8c44-36d59b6a89f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
