<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Website</name>
   <tag></tag>
   <elementGuidId>d5684d58-e2e7-49de-8972-4bb3b1cf0750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uc_hover_text_reveal_content_box_elementor24486 > div.uc_long_content_box_holder > div.uc_long_content_box_box > div.uc_box_content > div.uc_hidden_content > a.uc_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uc_hover_text_reveal_content_box_elementor24486']/div/div/div[3]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e65d45b5-eb90-403f-b1d1-f4a2bd2e9e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://covid19.makassarkota.go.id</value>
      <webElementGuid>ce56c873-2f8d-4325-a159-481735910838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uc_btn</value>
      <webElementGuid>f1b5f192-c703-4352-848a-67ffbf0432d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>081cc267-2fdf-4ce3-b811-2c565a2049f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uc_hover_text_reveal_content_box_elementor24486&quot;)/div[@class=&quot;uc_long_content_box_holder&quot;]/div[@class=&quot;uc_long_content_box_box&quot;]/div[@class=&quot;uc_box_content&quot;]/div[@class=&quot;uc_hidden_content&quot;]/a[@class=&quot;uc_btn&quot;]</value>
      <webElementGuid>05315897-e560-44af-a5d0-9fcfe7954b50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uc_hover_text_reveal_content_box_elementor24486']/div/div/div[3]/div[2]/a</value>
      <webElementGuid>616eeda0-aba9-4ea2-8e62-055e38532e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Website')]</value>
      <webElementGuid>dadd9aaf-7a85-4e1d-8034-e5e8e6608ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info COVID-19'])[1]/following::a[1]</value>
      <webElementGuid>09578788-c668-49bd-b25b-fc71c5ed9224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon Sekarang'])[1]/following::a[1]</value>
      <webElementGuid>41588018-ae23-4782-b87e-976fc6d726bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PPID Kota Makassar'])[1]/preceding::a[1]</value>
      <webElementGuid>59c2dc9c-eefa-4823-b869-c4cfbeb4b513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[2]/preceding::a[1]</value>
      <webElementGuid>35cae7a0-2dcd-4359-8ab8-4b38ffe81aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Website']/parent::*</value>
      <webElementGuid>975ff1cd-2407-4c87-9761-3925ad88de34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://covid19.makassarkota.go.id')]</value>
      <webElementGuid>483c443b-cdef-4941-8d59-dfe60806d442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[3]/div[2]/a</value>
      <webElementGuid>e2313ce8-7db8-4b03-ba37-3f1486cba3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://covid19.makassarkota.go.id' and (text() = 'Website' or . = 'Website')]</value>
      <webElementGuid>525845fc-cf3d-4c27-af49-75930e99c57e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
