<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Website_1</name>
   <tag></tag>
   <elementGuidId>9d8332d7-7171-4d35-80cb-85704f132772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uc_hover_text_reveal_content_box_elementor30857 > div.uc_long_content_box_holder > div.uc_long_content_box_box > div.uc_box_content > div.uc_hidden_content > a.uc_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d4b1aca-ab6d-49ed-9973-ca38a8f877fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ppid.makassarkota.go.id</value>
      <webElementGuid>aa015cdd-f2bb-45a4-90fa-dae100471c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uc_btn</value>
      <webElementGuid>21a59b02-6e0d-49cf-a41b-1e4615678219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>91282dfd-57e5-467f-bf84-e95c445778c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uc_hover_text_reveal_content_box_elementor30857&quot;)/div[@class=&quot;uc_long_content_box_holder&quot;]/div[@class=&quot;uc_long_content_box_box&quot;]/div[@class=&quot;uc_box_content&quot;]/div[@class=&quot;uc_hidden_content&quot;]/a[@class=&quot;uc_btn&quot;]</value>
      <webElementGuid>ae61e436-df17-41e5-8d9c-9e7bb863979e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uc_hover_text_reveal_content_box_elementor30857']/div/div/div[3]/div[2]/a</value>
      <webElementGuid>84ab46c6-6337-4cf7-938a-414bee386e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Website')])[2]</value>
      <webElementGuid>5cb3184c-35df-41b4-a8fb-af0a3d4ae348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PPID Kota Makassar'])[1]/following::a[1]</value>
      <webElementGuid>dfad4e04-ce74-45d6-9c80-f4d6197b40cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[1]/following::a[1]</value>
      <webElementGuid>45f32c84-c44f-4ff6-93e6-0097bf3b6cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TENTANG MAKASSAR'])[1]/preceding::a[1]</value>
      <webElementGuid>4ec5900f-8f19-4b2a-94bd-2bade97684e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEKILAS MAKASSAR'])[1]/preceding::a[1]</value>
      <webElementGuid>4673b5c5-a122-4f0e-9406-2dea6d9c187a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ppid.makassarkota.go.id')]</value>
      <webElementGuid>f467c1f6-5c02-4f13-9114-9c91c69a9e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[3]/div[2]/a</value>
      <webElementGuid>6a8e4d36-04a9-454c-8944-87ad6b8746a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ppid.makassarkota.go.id' and (text() = 'Website' or . = 'Website')]</value>
      <webElementGuid>94e9de14-c16a-405f-bc3a-57f1b3c4db15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
