<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_dih.makassarkota.go.id_elementor-toggle-i_255990</name>
   <tag></tag>
   <elementGuidId>5d20907f-b459-4267-9c10-1ba61d81221b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17610 > span.elementor-toggle-icon.elementor-toggle-icon-left > span.elementor-toggle-icon-opened > i.elementor-toggle-icon-opened.fas.fa-caret-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17610']/span/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b4334b65-7b72-4c21-9f0c-b97a78c11bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-toggle-icon-opened fas fa-caret-up</value>
      <webElementGuid>db3708b4-a38d-4856-874c-7de024d7825d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17610&quot;)/span[@class=&quot;elementor-toggle-icon elementor-toggle-icon-left&quot;]/span[@class=&quot;elementor-toggle-icon-opened&quot;]/i[@class=&quot;elementor-toggle-icon-opened fas fa-caret-up&quot;]</value>
      <webElementGuid>77d7df4a-a8db-48bb-834e-235394dbce40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17610']/span/span[2]/i</value>
      <webElementGuid>562172b6-4f49-47e7-9749-dba77fd50989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/span/span[2]/i</value>
      <webElementGuid>a73c30c6-f1ff-4221-ba62-6d7a70dac8ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
