<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_explore.makassarkota.go.id_fas fa-caret-right</name>
   <tag></tag>
   <elementGuidId>a0bd2c1f-b4dc-437c-a942-e25d6941b8ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-17611 > span.elementor-toggle-icon.elementor-toggle-icon-left > span.elementor-toggle-icon-closed > i.fas.fa-caret-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-17611']/span/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dba8cf19-99c8-4392-9a98-d4de97775394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-caret-right</value>
      <webElementGuid>29da8cc7-1f68-42e2-83db-416da505a814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-17611&quot;)/span[@class=&quot;elementor-toggle-icon elementor-toggle-icon-left&quot;]/span[@class=&quot;elementor-toggle-icon-closed&quot;]/i[@class=&quot;fas fa-caret-right&quot;]</value>
      <webElementGuid>c18272ef-e5e6-492a-b82a-1215c4ba6d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-17611']/span/span/i</value>
      <webElementGuid>17d9b60c-7001-4052-9ed3-ee233f42282b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/span/span/i</value>
      <webElementGuid>4ca12eff-8ed2-4806-b96d-f9581074827e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
