<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_manggalakec.makassarkota.go.id_fas fa-car_9d3936</name>
   <tag></tag>
   <elementGuidId>0b882581-a802-4381-9c26-678584e5c7c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.elementor.elementor-12710 > section.elementor-section.elementor-top-section.elementor-element.elementor-element-5b865288.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default > div.elementor-container.elementor-column-gap-default > div.elementor-column.elementor-col-100.elementor-top-column.elementor-element.elementor-element-451ffef4 > div.elementor-widget-wrap.elementor-element-populated > div.elementor-element.elementor-element-6cf29109.elementor-widget.elementor-widget-toggle > div.elementor-widget-container > div.elementor-toggle > div.elementor-toggle-item > #elementor-tab-title-1826 > span.elementor-toggle-icon.elementor-toggle-icon-left > span.elementor-toggle-icon-closed > i.fas.fa-caret-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='elementor-tab-title-1826']/span/span/i)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c162f649-4e58-499b-8087-d3420360eaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-caret-right</value>
      <webElementGuid>62f97972-3099-4b77-9333-02af0a5b15b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uc_content_accordion_elementor93345&quot;)/div[@class=&quot;uc_container&quot;]/div[@class=&quot;uc_ac_box&quot;]/div[@class=&quot;uc_content&quot;]/div[@class=&quot;elementor elementor-12710&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-5b865288 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-451ffef4&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-6cf29109 elementor-widget elementor-widget-toggle&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-toggle&quot;]/div[@class=&quot;elementor-toggle-item&quot;]/div[@id=&quot;elementor-tab-title-1826&quot;]/span[@class=&quot;elementor-toggle-icon elementor-toggle-icon-left&quot;]/span[@class=&quot;elementor-toggle-icon-closed&quot;]/i[@class=&quot;fas fa-caret-right&quot;]</value>
      <webElementGuid>3cf4d323-70d1-4147-a63d-a14974484a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='elementor-tab-title-1826']/span/span/i)[3]</value>
      <webElementGuid>909336ca-767e-46fc-9873-d478ee863137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/div/section/div/div/div/div/div/div/div[6]/div/span/span/i</value>
      <webElementGuid>e12b3885-0f0b-4120-a6d6-b43b2627f3dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
