<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ongkog_attachment-medium size-medium</name>
   <tag></tag>
   <elementGuidId>91ffa1e0-3e72-467f-987c-6c9c13dc4c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium.size-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://makassarkota.go.id/wp-content/uploads/2019/12/LOGO-KOTA-MAKASSAR-e1583291072823.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e29e71f5-11a5-488f-ad75-72fb261c84c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>163</value>
      <webElementGuid>13357d2e-fd43-40c9-bd1e-1e30799dd11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>bfcc8901-2efb-49c6-ad06-2b41ca64b89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://makassarkota.go.id/wp-content/uploads/2019/12/LOGO-KOTA-MAKASSAR-e1583291072823.png</value>
      <webElementGuid>44cc73cd-c0f4-49e4-8641-a40cd7d7e9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium</value>
      <webElementGuid>c8cacc22-3601-48cd-a058-24d2ffaaec14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d60d969a-77ef-4f9d-bc48-5cca0ada4ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>0bef7861-5f48-4a83-9183-391cdaaff657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;background-fixed&quot;]/body[@class=&quot;home page-template page-template-elementor_canvas page page-id-12109 wp-custom-logo wp-embed-responsive group-blog inspiro-front-page has-header-image inspiro--with-page-nav page-layout-full-width post-display-content-excerpt full-height-iframe-video colors-custom elementor-default elementor-template-canvas elementor-kit-11435 elementor-page elementor-page-12109 inspiro-page-ready e--ua-blink e--ua-chrome e--ua-webkit inspiro-page-loaded&quot;]/div[@class=&quot;elementor elementor-12109&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-f439961 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-f0c4e9d&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-6c52cf2 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-medium size-medium&quot;]</value>
      <webElementGuid>85cc8185-5503-4953-b589-8946ad4c0065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://makassarkota.go.id/wp-content/uploads/2019/12/LOGO-KOTA-MAKASSAR-e1583291072823.png')]</value>
      <webElementGuid>fa5161db-5e79-48e0-8e74-e4ce3f6c546f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5a5ee6b4-7219-4211-9733-3faf11378c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://makassarkota.go.id/wp-content/uploads/2019/12/LOGO-KOTA-MAKASSAR-e1583291072823.png']</value>
      <webElementGuid>d7a50aee-a839-4e9f-8a68-c7bf6bf68704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
