<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PETA  WILAYAH ADMINISTRASI KOTA MAKASS_464718</name>
   <tag></tag>
   <elementGuidId>f7d4b296-a499-40fa-a9b6-2435022c3979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.uc-heading.uc_trigger-uc_content_accordion_elementor59688 > span.uc_dactive.bbb.heading-padding.ue_accordion_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uc_content_accordion_elementor59688']/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1527eac-7e8e-44b5-bf3c-ffc32857140f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uc_dactive bbb heading-padding ue_accordion_icon</value>
      <webElementGuid>9f237f1f-6a97-49cc-ba28-9482fbdab304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uc_content_accordion_elementor59688&quot;)/div[@class=&quot;uc_container&quot;]/div[@class=&quot;uc_ac_box&quot;]/div[@class=&quot;uc-heading uc_trigger-uc_content_accordion_elementor59688&quot;]/span[@class=&quot;uc_dactive bbb heading-padding ue_accordion_icon&quot;]</value>
      <webElementGuid>5d4315d9-d985-47b4-8d3b-f0ba8ade2dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a3828e8c-9c3c-4dc1-beb0-fdd05b164dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uc_dactive bbb heading-padding ue_accordion_icon</value>
      <webElementGuid>f4f069c3-2f51-4088-9b15-a69dcf9f64e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uc_content_accordion_elementor51707&quot;)/div[@class=&quot;uc_container&quot;]/div[@class=&quot;uc_ac_box&quot;]/div[@class=&quot;uc-heading uc_trigger-uc_content_accordion_elementor51707&quot;]/span[@class=&quot;uc_dactive bbb heading-padding ue_accordion_icon&quot;]</value>
      <webElementGuid>57467532-2b2f-407d-b45d-c75f565d8ea8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uc_content_accordion_elementor59688']/div/div/div/span</value>
      <webElementGuid>c2bb5900-4104-41f4-b6ac-37586303434f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEJARAH PEMERINTAH KOTA MAKASSAR'])[1]/following::span[1]</value>
      <webElementGuid>fd31417b-72f3-4351-b4f4-b02f1fea2735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APBD'])[1]/preceding::span[2]</value>
      <webElementGuid>e17a5970-dc17-4079-85b7-f68a2a9c529c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORGANISASI PERANGKAT DAERAH'])[1]/preceding::span[2]</value>
      <webElementGuid>907103f8-dacf-4a10-8962-27d9e97f2d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/span</value>
      <webElementGuid>2062186c-64d8-4ae0-8f74-fc6bf44bd5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uc_content_accordion_elementor51707']/div/div/div/span</value>
      <webElementGuid>0f451b36-a8f6-4c5d-974e-082509e92a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
